#include "bitwise.hpp"
using namespace std;

void logical_not_stack(std::string * prev_loc, int * cond, int * maxCond, int q_flag){
    cout << *prev_loc << ", " << *cond << ", " << "rm_1\n";
    cout << "rm_1" << ", " << *cond << ", " << "rm_2\n";
    cout << "rm_2" << ", " << *cond << ", " << "hall_13_2\n";
    cout << "hall_13_2" << ", " << *cond << ", " << "lecture_hall_eq\n";

    cout << "lecture_hall_eq_t" << ", " << *cond << ", " << "kd_1\n";
    cout << "kd_1" << ", " << *cond << ", " << "kd_2\n";
    cout << "kd_2" << ", " << *cond << ", " << "oat_stage[1]\n";
    cout << "oat_stage" << ", " << *cond + 1 << ", " << "hall_13_2\n";
    cout << "hall_13_2" << ", " << *cond + 1 << ", " << "oat_stairs_2\n";
    cout << "oat_stairs_2" << ", " << *cond + 1<< ", " << "oat_stage[3]\n";
    
    cout << "lecture_hall_eq_f" << ", " << *cond << ", " << "oat_stage[2]\n";
    cout << "oat_stage" << ", " << *cond + 2 << ", " << "kd_1\n";
    cout << "kd_1" << ", " << *cond + 2 << ", " << "kd_2\n";
    cout << "kd_2" << ", " << *cond + 2 << ", " << "oat_stage[1]\n";
    cout << "oat_stage" << ", " << *cond + 3 << ", " << "hall_13_2\n";
    if(!q_flag)
        cout << "hall_13_2" << ", " << *cond + 3 << ", " << "oat_stage[1]\n";
    else
        cout << "hall_13_2" << ", " << *cond + 3 << ", " << "finish\n";
    *cond = *cond + 4;
    *prev_loc = "oat_stage";
    *maxCond = max(*cond, *maxCond);
}


void not_stack(std::string * prev_loc, int * cond, int * maxCond, int q_flag){
    cout << *prev_loc << ", " << *cond + 0 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 0 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 0 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 0 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 0 << ", " << "hall_13_3" << endl;
    cout << "hall_13_3" << ", " << *cond + 0 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 0 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 1 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 1 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 1 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 1 << ", " << "hall_13_1" << endl;
    cout << "hall_13_1" << ", " << *cond + 1 << ", " << "oat_stairs_1" << endl;
    cout << "oat_stairs_1" << ", " << *cond + 1 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 1 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 1 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 1 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 1 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 1 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 2 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 2 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 3 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 3 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 4 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 4 << ", " << "eshop_2" << endl;
    cout << "eshop_2" << ", " << *cond + 4 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 4 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 4 << ", " << "hall_3" << endl;
    cout << "hall_3" << ", " << *cond + 4 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 4 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 4 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 4 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 5 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 5 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 5 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 5 << ", " << "southern_labs_2" << endl;
    cout << "southern_labs_2" << ", " << *cond + 5 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 6 << ", " << "southern_labs_2" << endl;
    cout << "southern_labs_2" << ", " << *cond + 6 << ", " << "hall_3" << endl;
    cout << "hall_3" << ", " << *cond + 6 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 6 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 6 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 6 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 6 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 7 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 7 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 7 << ", " << "southern_labs_2" << endl;
    cout << "southern_labs_2" << ", " << *cond + 7 << ", " << "hall_3" << endl;
    cout << "hall_3" << ", " << *cond + 7 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 8 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 8 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 8 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 9 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 9 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 9 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 9 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 9 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 10 << ", " << "kd_1" << endl;
    if(!q_flag)
        cout << "kd_1" << ", " << *cond + 10 << ", " << "oat_stage[1]\n";
    else
        cout << "kd_1" << ", " << *cond << ", " << "finish\n";
    *cond += 11;
    *prev_loc = "oat_stage";
    *maxCond = max(*cond, *maxCond);

}


void and_stack(std::string * prev_loc, int * cond, int * maxCond, int q_flag){

    cout << *prev_loc << ", " << *cond + 0 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 0 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 0 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 0 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 0 << ", " << "hall_13_3" << endl;
    cout << "hall_13_3" << ", " << *cond + 0 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 0 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 1 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 1 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 1 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 1 << ", " << "hall_13_1" << endl;
    cout << "hall_13_1" << ", " << *cond + 1 << ", " << "oat_stairs_1" << endl;
    cout << "oat_stairs_1" << ", " << *cond + 1 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 1 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 1 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 1 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 1 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 1 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 2 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 2 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 3 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 3 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 4 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 4 << ", " << "eshop_2" << endl;
    cout << "eshop_2" << ", " << *cond + 4 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 4 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 4 << ", " << "hall_3" << endl;
    cout << "hall_3" << ", " << *cond + 4 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 4 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 4 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 4 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 6 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 6 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 6 << ", " << "oat_stage[-1]" << endl;
    cout << "oat_stage" << ", " << *cond + 5 << ", " << "lecture_hall_eq" << endl;
    cout << "lecture_hall_eq_t" << ", " << *cond + 5 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 7 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 7 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 7 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 7 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 7 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 7 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 7 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 7 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 8 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 8 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 8 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 8 << ", " << "rm_3" << endl;
    cout << "lecture_hall_eq_f" << ", " << *cond + 5 << ", " << "oat_stage[5]" << endl;
    cout << "oat_stage" << ", " << *cond + 10 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 10 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 10 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 10 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 11 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 11 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 11 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 11 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 11 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 11 << ", " << "oat_stage[6]" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 11 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 12 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 12 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 12 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 12 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 12 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 12 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 13 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 13 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 13 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 13 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 13 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 13 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 13 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 14 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 14 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 14 << ", " << "oat_stage[3]" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 10 << ", " << "oat_stage[5]" << endl;
    cout << "oat_stage" << ", " << *cond + 15 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 15 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 15 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 15 << ", " << "oat_stage[2]" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 15 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 16 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 16 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 16 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 16 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 17 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 17 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 17 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 18 << ", " << "mt_3_2" << endl;
    cout << "mt_3_2" << ", " << *cond + 18 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 18 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 18 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 18 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 18 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 19 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 19 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 19 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 19 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 19 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 19 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 19 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 19 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 19 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 20 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 20 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 21 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 21 << ", " << "oat_stage[-16]" << endl;
    if(!q_flag)
        cout << "rm_3" << ", " << *cond + 8 << ", " << "oat_stage[14]" << endl;
    else
        cout << "rm_3" << ", " << *cond << ", " << "finish\n";
    *cond += 22;
    *prev_loc = "oat_stage";
    *maxCond = max(*cond, *maxCond);
}

void xor_stack(std::string * prev_loc, int * cond, int * maxCond, int q_flag){

    cout << *prev_loc << ", " << *cond + 0 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 0 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 0 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 0 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 0 << ", " << "hall_13_3" << endl;
    cout << "hall_13_3" << ", " << *cond + 0 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 0 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 1 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 1 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 1 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 1 << ", " << "hall_13_1" << endl;
    cout << "hall_13_1" << ", " << *cond + 1 << ", " << "oat_stairs_1" << endl;
    cout << "oat_stairs_1" << ", " << *cond + 1 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 1 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 1 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 1 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 1 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 1 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 2 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 2 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 3 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 3 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 4 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 4 << ", " << "eshop_2" << endl;
    cout << "eshop_2" << ", " << *cond + 4 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 4 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 4 << ", " << "hall_3" << endl;
    cout << "hall_3" << ", " << *cond + 4 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 4 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 4 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 4 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 6 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 6 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 6 << ", " << "oat_stage[-1]" << endl;
    cout << "oat_stage" << ", " << *cond + 5 << ", " << "lecture_hall_eq" << endl;
    cout << "lecture_hall_eq_t" << ", " << *cond + 5 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 7 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 7 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 7 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 7 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 7 << ", " << "rm_3" << endl;
    cout << "lecture_hall_eq_f" << ", " << *cond + 5 << ", " << "oat_stage[3]" << endl;
    cout << "oat_stage" << ", " << *cond + 8 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 8 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 8 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 8 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 9 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 9 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 9 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 9 << ", " << "oat_stage[10]" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 9 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 10 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 10 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 10 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 11 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 11 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 11 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 11 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 11 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 11 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 11 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 12 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 12 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 12 << ", " << "mt_3_2" << endl;
    cout << "mt_3_2" << ", " << *cond + 12 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 12 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 12 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 12 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 13 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 13 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 13 << ", " << "oat_stage[6]" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 8 << ", " << "oat_stage[6]" << endl;
    cout << "oat_stage" << ", " << *cond + 14 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 14 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 14 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 14 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 14 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 15 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 15 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 15 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 15 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 15 << ", " << "oat_stage[4]" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 14 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 16 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 16 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 16 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 16 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 16 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 16 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 16 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 17 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 17 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 17 << ", " << "mt_3_2" << endl;
    cout << "mt_3_2" << ", " << *cond + 17 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 17 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 17 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 17 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 18 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 18 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 18 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 19 << ", " << "mt_3_2" << endl;
    cout << "mt_3_2" << ", " << *cond + 19 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 19 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 19 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 19 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 19 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 20 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 20 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 20 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 20 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 20 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 20 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 20 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 20 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 21 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 21 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 21 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 21 << ", " << "oat_stage[-16]" << endl;
    if(!q_flag)
        cout << "rm_3" << ", " << *cond + 7 << ", " << "oat_stage[15]" << endl;
    else
        cout << "rm_3" << ", " << *cond << ", " << "finish\n";
    *cond += 22;
    *prev_loc = "oat_stage";
    *maxCond = max(*cond, *maxCond);

}


void or_stack(std::string * prev_loc, int * cond, int * maxCond, int q_flag){

    cout << *prev_loc << ", " << *cond + 0 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 0 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 0 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 0 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 0 << ", " << "hall_13_3" << endl;
    cout << "hall_13_3" << ", " << *cond + 0 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 0 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 1 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 1 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 1 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 1 << ", " << "hall_13_1" << endl;
    cout << "hall_13_1" << ", " << *cond + 1 << ", " << "oat_stairs_1" << endl;
    cout << "oat_stairs_1" << ", " << *cond + 1 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 1 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 1 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 1 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 1 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 1 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 2 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 2 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 3 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 3 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 4 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 4 << ", " << "eshop_2" << endl;
    cout << "eshop_2" << ", " << *cond + 4 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 4 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 4 << ", " << "hall_3" << endl;
    cout << "hall_3" << ", " << *cond + 4 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 4 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 4 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 4 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 6 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 6 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 6 << ", " << "oat_stage[-1]" << endl;
    cout << "oat_stage" << ", " << *cond + 5 << ", " << "lecture_hall_eq" << endl;
    cout << "lecture_hall_eq_t" << ", " << *cond + 5 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 7 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 7 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 7 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 7 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 7 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 7 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 7 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 7 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 8 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 8 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 8 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 8 << ", " << "rm_3" << endl;
    cout << "lecture_hall_eq_f" << ", " << *cond + 5 << ", " << "oat_stage[5]" << endl;
    cout << "oat_stage" << ", " << *cond + 10 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 10 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 10 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 10 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 11 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 11 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 11 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 11 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 11 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 11 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 11 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 11 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 11 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 12 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 12 << ", " << "mt_3_2" << endl;
    cout << "mt_3_2" << ", " << *cond + 12 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 12 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 12 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 12 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 12 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 13 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 13 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 13 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 13 << ", " << "oat_stage[7]" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 12 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 14 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 14 << ", " << "oat_stage[6]" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 10 << ", " << "oat_stage[5]" << endl;
    cout << "oat_stage" << ", " << *cond + 15 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 15 << ", " << "lecture_hall_lt" << endl;
    cout << "lecture_hall_lt_t" << ", " << *cond + 15 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 15 << ", " << "oat_stage[5]" << endl;
    cout << "lecture_hall_lt_f" << ", " << *cond + 15 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 16 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 16 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 16 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 16 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 16 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 16 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 17 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 17 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 17 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 17 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 17 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 18 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 18 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 18 << ", " << "mt_3_2" << endl;
    cout << "mt_3_2" << ", " << *cond + 18 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 18 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 18 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 19 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 19 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 19 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 19 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 20 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 20 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 20 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 21 << ", " << "mt_3_2" << endl;
    cout << "mt_3_2" << ", " << *cond + 21 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 21 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 21 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 21 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 21 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 22 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 22 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 22 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 22 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 22 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 22 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 22 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 22 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 22 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 23 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 23 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 24 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 24 << ", " << "oat_stage[-19]" << endl;
    if(!q_flag)
        cout << "rm_3" << ", " << *cond + 8 << ", " << "oat_stage[17]" << endl;
    else
        cout << "rm_3" << ", " << *cond << ", " << "finish\n";
    *cond += 25;
    *prev_loc = "oat_stage";
    *maxCond = max(*cond, *maxCond);

}

void nand_stack(std::string * prev_loc, int * cond, int * maxCond, int q_flag){

    cout << *prev_loc << ", " << *cond + 0 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 0 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 0 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 0 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 1 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 1 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 1 << ", " << "hall_13_1" << endl;
    cout << "hall_13_1" << ", " << *cond + 1 << ", " << "oat_stairs_1" << endl;
    cout << "oat_stairs_1" << ", " << *cond + 1 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 1 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 1 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 1 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 1 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 1 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 2 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 2 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 3 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 3 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 4 << ", " << "eshop_1" << endl;
    cout << "eshop_1" << ", " << *cond + 4 << ", " << "eshop_2" << endl;
    cout << "eshop_2" << ", " << *cond + 4 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 4 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 4 << ", " << "hall_3" << endl;
    cout << "hall_3" << ", " << *cond + 4 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 4 << ", " << "hall_13_1" << endl;
    cout << "hall_13_1" << ", " << *cond + 4 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 4 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 4 << ", " << "hall_13_3" << endl;
    cout << "hall_13_3" << ", " << *cond + 4 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 4 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 4 << ", " << "oat_stage[8]" << endl;
    cout << "oat_stage" << ", " << *cond + 12 << ", " << "lecture_hall_gt" << endl;
    cout << "lecture_hall_gt_f" << ", " << *cond + 12 << ", " << "lecture_hall_eq" << endl;
    cout << "lecture_hall_eq_f" << ", " << *cond + 12 << ", " << "oat_stage[-5]" << endl;
    cout << "oat_stage" << ", " << *cond + 7 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 7 << ", " << "lecture_hall_gt" << endl;
    cout << "lecture_hall_gt_t" << ", " << *cond + 7 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 7 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 7 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 7 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 7 << ", " << "rm_1" << endl;
    cout << "lecture_hall_gt_f" << ", " << *cond + 7 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 7 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 7 << ", " << "mt_2_3" << endl;
    cout << "mt_2_3" << ", " << *cond + 7 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 9 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 9 << ", " << "hall_2" << endl;
    cout << "hall_2" << ", " << *cond + 9 << ", " << "oat_stage[1]" << endl;
    cout << "lecture_hall_gt_t" << ", " << *cond + 12 << ", " << "kd_3" << endl;
    cout << "lecture_hall_eq_t" << ", " << *cond + 12 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 12 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 12 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 12 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 12 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 12 << ", " << "oat_stage[-7]" << endl;
    cout << "oat_stage" << ", " << *cond + 5 << ", " << "lecture_hall_gt" << endl;
    cout << "lecture_hall_gt_f" << ", " << *cond + 5 << ", " << "lecture_hall_eq" << endl;
    cout << "lecture_hall_eq_f" << ", " << *cond + 5 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 5 << ", " << "oat_stage[2]" << endl;
    cout << "lecture_hall_gt_t" << ", " << *cond + 5 << ", " << "oat_stage[1]" << endl;
    cout << "lecture_hall_eq_t" << ", " << *cond + 5 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 6 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 6 << ", " << "hall_5" << endl;
    cout << "hall_5" << ", " << *cond + 6 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 6 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 6 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 6 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 8 << ", " << "rm_1" << endl;
    cout << "rm_1" << ", " << *cond + 8 << ", " << "rm_2" << endl;
    cout << "rm_2" << ", " << *cond + 8 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 10 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 10 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 10 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 11 << ", " << "oat_stairs_2" << endl;
    cout << "oat_stairs_2" << ", " << *cond + 11 << ", " << "kd_3" << endl;
    cout << "kd_3" << ", " << *cond + 11 << ", " << "hall_12" << endl;
    cout << "hall_12" << ", " << *cond + 11 << ", " << "mt_1_3" << endl;
    cout << "mt_1_3" << ", " << *cond + 11 << ", " << "hall_13_2" << endl;
    cout << "hall_13_2" << ", " << *cond + 11 << ", " << "rm_3" << endl;
    cout << "rm_3" << ", " << *cond + 11 << ", " << "lecture_hall_eq" << endl;
    cout << "lecture_hall_eq_f" << ", " << *cond + 11 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 11 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 11 << ", " << "oat_stage[1]" << endl;
    cout << "lecture_hall_eq_t" << ", " << *cond + 11 << ", " << "oat_stage[2]" << endl;
    cout << "oat_stage" << ", " << *cond + 13 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 13 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 13 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 14 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 14 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 14 << ", " << "oat_stage[1]" << endl;
    cout << "oat_stage" << ", " << *cond + 15 << ", " << "kd_1" << endl;
    cout << "kd_1" << ", " << *cond + 15 << ", " << "kd_2" << endl;
    cout << "kd_2" << ", " << *cond + 15 << ", " << "mt_2_3" << endl;
    if(!q_flag)
        cout << "mt_2_3" << ", " << *cond + 15 << ", " << "oat_stage[1]\n";
    else
        cout << "mt_2_3" << ", " << *cond << ", " << "finish\n";
    *cond += 16;
    *prev_loc = "oat_stage";
    *maxCond = max(*cond, *maxCond);

}